blank_issues_enabled: false
contact_links:
  - name: GitHub Discussions
    url: https://github.com/orgs/0x6flab/discussions
    about: Join in-depth discussions. Ask questions, share your experiences, and connect with other maintainers and community members.
